services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - /tmp/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=app
      - TZ=America/Argentina/Mendoza

  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - HOST=postgres 
